### ISSUE TITLE
 Very useful, but a couple of issues

### ISSUE THREAD

**Issue by KTS915** [bamadesigner/wA11y#3]
I posted this on wordpress.org, but apparently you prefer to have issues reported here.

This is a very useful tool. Thank you. (Some users might let it become their master, but that would be their mistake, not yours.)

I have noticed two issues. The first is that, using tota11y, it really can’t cope with forms. It sees the background for form fields as the font color, and doesn’t appear to see the true font color at all. Perhaps that’s a problem with tota11y rather than with wA11y, so I’m not sure whether you can do much about it.

The second issue is with your rather clever, if still experimental, wand. I notice that, currently, the wand recognizes hover events, although these are mouse events that, so far as I am aware, would not be recognized by a screen reader. On the other hand, the wand does not recognize focus events, when these would be detected by a screen reader.

Thanks again!

**Comment by bamadesigner** [comment]
Hi again! It looks like your issues are with the tota11y tool. If you're still seeing issues, please report at https://github.com/Khan/tota11y. Thanks!
