### ISSUE TITLE
When using javascript, wand and link test don't match

### ISSUE THREAD

**Issue by KTS915** [bamadesigner/wA11y#4]
If I use jQuery to add meaningful language (within a span with the class of "screen-reader-text") to a link, the Screen Reader Wand sees the text, and the Link Text check reports the code as present in its "Relevant code:" box, which is as expected.

However, the Link Text check nevertheless continues to report that the text is unclear.

**Comment by bamadesigner** [comment]
@KTS915 Your issue is probably with the tota11y tool, which is maintained separately from Wa11y. If you're still having the issue, please report to tota11y. Thanks! https://github.com/Khan/tota11y
